# Use root/password as user/password credentials
version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1
    container_name: jaeger
    restart: always
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
      - "14269:14269"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
