receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  # Data sources: traces
  jaeger:
    endpoint: "jaeger:14250" # point to jaeger-agent to send spans in model.proto format.
    tls:
      insecure: true

  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger, logging]
